// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestProyect.Data;

namespace TestProyect.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211021060003_Administrativo")]
    partial class Administrativo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestProyect.Models.Administrativos", b =>
                {
                    b.Property<int>("IdAdministrativos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdscripcionAdminId")
                        .HasColumnType("int");

                    b.Property<bool>("CambioPwAdministrativo")
                        .HasColumnType("bit");

                    b.Property<string>("CasaAdministrativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CelularAdministrativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdministrativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<string>("MaternoAdministrativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatriculaAdministrativo")
                        .HasColumnType("int");

                    b.Property<string>("NombreAdministrativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordAdministrativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaternoAdministrativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ValidacionAdministrativo")
                        .HasColumnType("bit");

                    b.HasKey("IdAdministrativos");

                    b.HasIndex("AdscripcionAdminId");

                    b.HasIndex("IdEstatus");

                    b.ToTable("Administrativos");
                });

            modelBuilder.Entity("TestProyect.Models.Adscripcion", b =>
                {
                    b.Property<int>("IdAdscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstatusId")
                        .HasColumnType("int");

                    b.Property<string>("NombreAdscripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAdscripcion");

                    b.HasIndex("EstatusId");

                    b.ToTable("Adscripcion");
                });

            modelBuilder.Entity("TestProyect.Models.Estatus", b =>
                {
                    b.Property<int>("IdEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreEstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstatus");

                    b.ToTable("Estatus");
                });

            modelBuilder.Entity("TestProyect.Models.Administrativos", b =>
                {
                    b.HasOne("TestProyect.Models.Adscripcion", "Adscripcion")
                        .WithMany()
                        .HasForeignKey("AdscripcionAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProyect.Models.Estatus", "Estatus")
                        .WithMany()
                        .HasForeignKey("IdEstatus");

                    b.Navigation("Adscripcion");

                    b.Navigation("Estatus");
                });

            modelBuilder.Entity("TestProyect.Models.Adscripcion", b =>
                {
                    b.HasOne("TestProyect.Models.Estatus", "Estatus")
                        .WithMany()
                        .HasForeignKey("EstatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estatus");
                });
#pragma warning restore 612, 618
        }
    }
}
